### PR TITLE
Fix default link style color and remove `FlLinkStyle.useGradient` in favor of checking if `FlLinkStyle.gradient` is null

### LINKED ISSUE #76: [BUG] Default link style causes NRE when painting temp link
#### Description 🖊️

When trying to link a port that uses the default link style, trying to draw a link results in a null-check failing in `NodeEditorRenderBox._paintBezierLink`.

#### Steps to Reproduce 🔄

Register a node with a port that doesn't specify `style`, create one in the editor, and try to link that port.

#### Expected Behavior ✅

The link shows correctly with the default link style (solid blue bezier curve of width 2), whether as a temporary link or when connected to another port.

#### Actual Behavior ❌

Flutter complains about a null-check failure in `NodeEditorRenderObjectWidget`/`NodeEditorRenderBox`, the "link" doesn't get painted / is invisible, and then trying to move the link creates even more null exceptions (printing `Another exception was thrown: Null check operator used on a null value` in the log).

#### Screenshots 📸

https://github.com/user-attachments/assets/039c67cf-44ba-4b03-8e7d-183db97dccc8

(don't mind the grid disappearing thing, it's the LOD bug fixed by #75)

### Pre-Issue Creation Checklist 📝

Before submitting an issue, please ensure you’ve completed the following:

- [x] Have you checked if the issue already exists in the backlog or open issues? 🔍
- [x] Have you updated to the latest version of the package and confirmed the issue persists? 🔄
- [x] Is your issue related to one of the following? (Please check all that apply):
  - [ ] Documentation inaccuracies or missing details 📚
  - [ ] Localization or accessibility issues 🌐
  - [x] Node editor UI/UX problems 🎨
  - [ ] Core functionality or features of the package 💻

### PR DESCRIPTION
**Pull request by blokyk**
Fixes #76

Broken up into two commits:
- the first one (`fix: assert link color is set if it doesn't use gradient`) fixes the declaration of `defaultLinkStyle` and adds an assert to `FlLinkStyle`'s ctor to make sure `color` is non-null if `useGradient` is false
- the second one (`refact!: replace linkstyle's useGradient with null-checking gradient/color`) removes `useGradient`, and changes the rest of the codebase to check if `gradient != null` instead. It also adds an assert to make sure at least one of `color` or `gradient` is set (though it doesn't check *only one* of these is set, since the rest of the codebase sometimes checks "one of" and sometimes "only one")

You can cherry-pick only the first one if you disagree with the decision to remove `useGradient`, it's a breaking change after all!

### CODE REVIEW

**Comment by Blokyk** [comment]
wrt to the "only one is non-null" thing: I was wondering why you don't tend to use separate constructors in this codebase? IMO it would definitely make sense to have a `FlLinkStyle.gradient`/`FlLinkStyle.color` pair of constructors

File: example/lib/nodes.dart [hunk 1]
```diff
@@ -14,17 +14,11 @@ FlPortStyle outputDataPortStyle(state) => FlPortStyle(
...
         color: state.isSelected
             ? Colors.orangeAccent
             : state.isHovered
                 ? Colors.limeAccent
                 : Colors.deepOrange,
-        gradient: const LinearGradient(
-          colors: [Colors.deepOrange, Colors.purple],
-          begin: Alignment.centerLeft,
-          end: Alignment.centerRight,
-        ),
```
Comment (Blokyk) [inline example/lib/nodes.dart:27]: I removed the `gradient` values there cause you're not really supposed to specify both with the second commit.

However, from my understanding this is supposed to serve as a demo of the fact links can have gradients, correct? So to keep that effect, I suggest either:
- commenting the `gradient` lines instead of removing them
- using gradients for only one of the ports
- having a file-local bool that the style builders use to decide whether it should give links gradients or solid colors

**Comment by WilliamKarolDiCioccio** [comment]
> wrt to the "only one is non-null" thing: I was wondering why you don't tend to use separate constructors in this codebase? IMO it would definitely make sense to have a `FlLinkStyle.gradient`/`FlLinkStyle.color` pair of constructors



> wrt to the "only one is non-null" thing: I was wondering why you don't tend to use separate constructors in this codebase? IMO it would definitely make sense to have a `FlLinkStyle.gradient`/`FlLinkStyle.color` pair of constructors

Hi @Blokyk! Thanks for your contribution. You're absolutely right, that would toatlly make sense. Do you want to take care of it? If yes, will you include it in this PR or create a new one?

**Comment by WilliamKarolDiCioccio** [comment]
I like the enthusiasm! Do it when you can, we're not in a rush 😄

**Comment by Blokyk** [comment]
Haha no worries, I'm just happy to contribute to a package I use that has potential like this! :) Plus it's a pretty minor change anyway, took barely 10 minutes to write/test/commit
